### ISSUE TITLE
Send command by device name not just hostname

### ISSUE THREAD

**Issue by brandonholland** [GadgetReactor/pyHS100#110]
It seems to be smarter to send a command based off the name that the device has internally.  I don't know if there's an easier way than to discover, enum through the devices to find the name to get the IP address which kind of slows down from broadcasts but removes the need to have reservations and static dns entries idc about that stuff I just want to reboot the "modem" plug reliably with no extra manual work / maintenance

**Comment by rytilahti** [comment]
That'd be doable by doing a discovery, and could very well be added to the cli tool, pull requests are welcome! However I wouldn't add that to the library interface itself.

**Comment by brandonholland** [comment]
The CLI tool would be great because that's all I plan to use myself I'm just going to have a basic internet script rebooting my modem when my internet fails seems like a lot of unnecessary work to have to deal with the low-level Plumbing to make sure my IP address hasn't changed first.

**Comment by brandonholland** [comment]
I'm just really trying to think about how I'd use this as an "end user" should i need to know all the details about dns and ip's and all of that when i just want to type "reboot device_name" of course I can spend the time to learn the python code which i prob will because i like to do this stuff but... actually i'd kind of like to query one time for device name then reboot by mac address really that way if i ever change the display name like an enduser it doesnt break everything and the mac will be a good unique ID that never changes.  Just trying to have a discussion from an enduser perspective.

**Comment by kwazel** [comment]
I just realized I had not even looked at the Issue list before doing  my merge request, but I think this issue has been fixed by [the most recent commit](https://github.com/GadgetReactor/pyHS100/commit/ce89c0d80090b7555ab1649a16c96151fb914323)

**Comment by rytilahti** [comment]
Indeed, thanks for noticing! This is fixed with PR #127!
