### ISSUE TITLE
"Reboot" command

### ISSUE THREAD

**Issue by brandonholland** [GadgetReactor/pyHS100#111]
Why not?

Turn off, check state, when off, turn on maybe even with an optional time to off?

**Comment by kirichkov** [comment]
I guess this is a feature request, targeted at the CLI.

My personal opinion is that this is beyond the scope of the project. This can be achieved easily in a bash script by having three lines, while it will require a lot more in python, and won't significantly contribute to the usability.

If you're interested in writing the code yourself and opening a pull request we can discuss it's usability and use cases.

**Comment by rytilahti** [comment]
There is also a reboot command, so if someone wants to add it, a PR will be accepted: https://github.com/softScheck/tplink-smartplug/blob/master/tplink-smarthome-commands.txt#L10

**Comment by kirichkov** [comment]
I think the OP wanted to reboot the device attached to the plug, not the plug itself, i.e. switch off the plug, and after a delay - switch it on.

**Comment by rytilahti** [comment]
Although that will be done when the plug gets rebooted, I just experimented a bit with it. So I think that PR will fix this issue (it allows also specifying a delay before rebooting it).
