### ISSUE TITLE
Continous Integration

### ISSUE THREAD

**Issue by mweinelt** [GadgetReactor/pyHS100#12]
We should set up some continous integration, like

- pylint
- flake8
- Hound-CI

It will help keep the code clean and make for a more consistent and easy review.

**Comment by kirichkov** [comment]
I second that. I'm very good at doing two-space instead of four-space indentation 😁

**Comment by GadgetReactor** [comment]
Hi guys, I am not familiar with continous integration, but would support it!

**Comment by kirichkov** [comment]
The idea is as soon new code is pushed, or pull request opened, it will automatically run a predefined list of "tests" and warn about it. I haven't used hound-ci, but apparently it comments on the pull request with the issues it found with the code, i.e. wrong formatting, syntax errors, etc.

**Comment by mweinelt** [comment]
@GadgetReactor Did you enable the Integration on https://houndci.com/ yet?

**Comment by rytilahti** [comment]
Seems to be activated, running tests with tox could also be nice besides that.

**Comment by rytilahti** [comment]
https://travis-ci.org/ could work for running the unittests. Should also be pretty straightforward to enable: http://docs.python-guide.org/en/latest/scenarios/ci/

**Comment by mweinelt** [comment]
@GadgetReactor Since we have a `.travis.yml` file now, thanks to @rytilahti, can you please head to https://travis-ci.org and activate integration for this repository?

**Comment by rytilahti** [comment]
Travis-ci is not very useful before #24 gets merged as it tries to test against a real device and just times out after an hour or so :) current state can be checked though for my branch: https://travis-ci.org/rytilahti/pyHS100/builds/189069663 -- py27 failing by not raising ValueError remains unknown for now, py34 and py35 builds are passing!

**Comment by rytilahti** [comment]
py27 is also now working, it required marking SmartPlug to be derived from object to let properties work for testing the state. https://travis-ci.org/rytilahti/pyHS100/builds/189107042

**Comment by rytilahti** [comment]
@GadgetReactor mind activating travis-ci.org for the repo now as tests are there, and closing this?

**Comment by GadgetReactor** [comment]
I think I have done it correctly this time, apologies for the delay.

**Comment by rytilahti** [comment]
Not a problem. Would you mind bumping the version number too after finishing merging the pull requests? We can then finally fix homeassistant component :-)

**Comment by kirichkov** [comment]
@rytilahti will you work on the home assistant pull request?

**Comment by rytilahti** [comment]
I can do that, but for it I'll need a newly tagged release. Before that it makes no sense tbh.

**Comment by kirichkov** [comment]
The version has been bumped in the `setup.py ` in https://github.com/GadgetReactor/pyHS100/commit/04185706f8355c26c94a8fac014633bf763ae9e4

**Comment by rytilahti** [comment]
Yes, I realized that too late.. Anyway, I created a new commit to add changelogs, unfortunately tags are not pullable so @GadgetReactor has to do the release handling: https://github.com/GadgetReactor/pyHS100/pull/28

**Comment by mweinelt** [comment]
@GadgetReactor In fact you should start tagging releases in Git. It's even possible from Githubs UI. Check out https://github.com/GadgetReactor/pyHS100/releases.

**Comment by GadgetReactor** [comment]
Ok - added the bump. I don't have access to my development machine these
few days. So a pull request to HA would have to wait till the weekend,
sorry! If someone can do it first, will be much appreciated!
