### ISSUE TITLE
python3.6: can't find '__main__' module in 'pyHS100'

### ISSUE THREAD

**Issue by omikun** [GadgetReactor/pyHS100#120]
Error occurs when I try: python3 pyHS100
I have to manually invoke python3 pyHS100/cli.py

Operating in mac os 11.12 with python 3.6 from homebrew.

**Comment by rytilahti** [comment]
The pyHS100 does not provide a `__main__`, but installs an entrypoint script to your binary directory:
```
$ which pyhs100 
/home/XXX/venv/bin/pyhs100
```
