### ISSUE TITLE
Socket Timeout

### ISSUE THREAD

**Issue by Raynman77** [GadgetReactor/pyHS100#132]
I keep getting a socket timeout exception raised when trying to issue a CLI command such as follows:

`pyhs100 --plug --ip xxx.xxx.x.xx off`

Or any CLI commands for that matter. Does this library not work on Windows 10 running python 3.6.3. I installed this library using pip. I'm trying to get this working with an HS100 device.

![image](https://user-images.githubusercontent.com/16449459/47057648-a3985c80-d18f-11e8-823a-c276171cfbcc.png)

**Comment by kirichkov** [comment]
This indicates that your machine can’t create connection to the socket.
Is the socket responding to pings from that same machine?
Maybe you have a firewall running?

**Comment by Raynman77** [comment]
Honestly haven't tried pinging it from this particular Windows machine. However, Discovery is not even finding anything. The firewall on the Windows machine is not blocking it.

**Comment by kirichkov** [comment]
That means your computer might not be in the same network as the socket. Wi-Fi connectivity might be spotty, etc.

**Comment by Raynman77** [comment]
My computer is in the same network and WiFi is not spotty at all. But that made me think that maybe since I have a Aprelium Abyss Webserver running on the same machine and it's default console port is 9999, that this might be conflicting. When I get home today, I will change the Abyss console port to something else and test the socket again to see if that was the case. I'll post back later today and hopefully we can call it day and close this issue.

**Comment by Raynman77** [comment]
That was the issue. Thanks @Kirichkov for your responses.

**Comment by kirichkov** [comment]
Haha. So the CLI was actually finding your own webserver! That would have never occurred to me! Good you figured it out!

**Comment by Raynman77** [comment]
Not just the CLI, but the whole library as well. The Abyss Webserver Console uses that port as a default for localhost tcp communication back to the console interface and the 2 cannot share that port for socket communication, atleast not at the same time. Lol
