### ISSUE TITLE
add support for the HS300

### ISSUE THREAD

**Issue by newAM** [GadgetReactor/pyHS100#134]
the HS300 is a power bar with 6 outlets that each have a relay and power monitoring.

**Comment by jimboca** [comment]
Duplicate of #131 I've started looking at this, but if you have more time to work on it you can take over?

**Comment by newAM** [comment]
**facepalm** sorry, I don't know how I missed the open one.  I'll take a closer look at it this weekend.

**Comment by jimboca** [comment]
No worries.  I've only had a little time to work on it, but discover is running, just need to work out how to reference each device, you can start with my Fork if you want https://github.com/jimboca/pyHS100
