### ISSUE TITLE
setting bulb alias

### ISSUE THREAD

**Issue by jman025** [GadgetReactor/pyHS100#138]
I am creating a python script with your module to control an LB110(US) bulb. Attempting to change its alias via `bulb.alias = "foo"` within python 3.5, does not change the result of `print(bulb.alias)`. Is there a reason for this. At the top of the script I am importing from pyHS100 import cli, smartbulb, smartdevice, protocon, and even smartplug.

`bulb.state = "OFF"` works just fine as well as the other bulb specific functions. Changing the alias the same way you would for the bulb state just isn't working.

**Comment by rytilahti** [comment]
That should change it, maybe you are calling your print too fast after the change? Can you try `pyhs100 alias <new alias>` and then `pyhs100 alias` to see if the cli tool works for you? When I added that it worked just fine on my HS110.

**Comment by rytilahti** [comment]
Please reopen if this is still an issue.
