### ISSUE TITLE
Issue receiving state of switch

### ISSUE THREAD

**Issue by hoveeman** [GadgetReactor/pyHS100#14]
I updated home assistant last night to .34 and it pulled down the latest pyHS100. My hs200 wall switches are now able to be controlled which is great! However, turning a hs100/hs110/hs200 on from home assistant turns the light on, but after a second, home assistant toggle flips to off. The light switch physically still stays on though. Reloading the ha interface shows the switch as off. I can tap to toggle it on and the switch physically stays on. If I tap it again to turn it off, it will turn off the switch. It appears as if it is unable to poll the device to receive its state after the last update.

**Comment by nickhx** [comment]
exact same problem here with my HS100 (UK) - sending a turn off or turn on command via home assistant works.  However, the toggle command turns on from the off state, but does not turn off again when turned on.

**Comment by smaggard** [comment]
I think is caused by the change in the code here
`        if relay_state == 0:
            return SWITCH_STATE_OFF
        elif relay_state == 1:
            return SWITCH_STATE_ON
        else:
            _LOGGER.warning("Unknown state %s returned.", relay_state)
            return SWITCH_STATE_UNKNOWN`

That method used to return simply 'ON', 'OFF', or 'UNKNOWN'  which home assistant could handle.

**Comment by nickhx** [comment]
@smaggard well done - the problem is that the SWITCH_STATE_OFF and SWITCH_STATE_ON variables are now defined as lowercase 'on' and 'off'.  In Home Assistant,  tplink.py is expecting uppercase 'ON' or 'OFF'.  So, should this library be updated or is it better to update tplink.py in Home Assistant?

**Comment by smaggard** [comment]
I think it would be easiest for the contributors currently making changes to simply change the values of the variables here, but I will leave that up to them.

**Comment by smaggard** [comment]
The following would fix the issue.

`        if relay_state == 0:
            return SWITCH_STATE_OFF.upper()
        elif relay_state == 1:
            return SWITCH_STATE_ON.upper()
        else:
            _LOGGER.warning("Unknown state %s returned.", relay_state)
            return SWITCH_STATE_UNKNOWN.upper()`

**Comment by mweinelt** [comment]
You are looking at the wrong versions. This is clearly before the changes you're mentioning.

Home-Assistant uses 0.2.1, which is based on https://github.com/GadgetReactor/pyHS100/commit/53c06ca7844f16d6ffe068f4ca01e8d5c707b9e3.

When @GadgetReactor puts out a new release, be it before or after the current pull request, I'll gladly update the home-assistant bindings myself.

**Comment by smaggard** [comment]
That is not the case. Is you upgrade home assistant it pulls those changes in.

**Comment by mweinelt** [comment]
Ouch, it indeed tracks the HEAD of this repository as `0.2.1`.

I've added a pullrequest to rollback the dependency upgrade. 
https://github.com/home-assistant/home-assistant/pull/4722

**Comment by mweinelt** [comment]
I address the on/off lowercasing issue here https://github.com/GadgetReactor/pyHS100/pull/15/files#diff-3475cfc85c1bad6f0bd35e52795d77e8R43. This should resolve your concerns, right?

Home-Assistant rolled back the pyHS100 Version and is now working again with 0.34.1.

**Comment by smaggard** [comment]
Yes it should

**Comment by rytilahti** [comment]
@hoveeman do you mind testing manually the newest master branch? do you mind posting the sysinfo output from python -m examples.cli for helping to debug the issue too? Thanks in advance!

**Comment by hoveeman** [comment]
@rytilahti Here is the attached debug from master connecting to a HS200 and HS110. I am personally struggling with trying to figure out how to control the switch and plug. What is the command that I need to use to be able to turn them on and off. 

HS200 Switch
`pi@pi:~/pyHS100 $ python3.4 -m examples.cli 10.0.0.9
DEBUG:pyHS100.pyHS100:> (31) {"system": {"get_sysinfo": {}}}
DEBUG:pyHS100.pyHS100:< (594) {"system":{"get_sysinfo":{"err_code":0,"sw_ver":"1.1.0 Build 160521 Rel.085826","hw_ver":"1.0","mic_type":"IOT.SMARTPLUGSWITCH","model":"HS200(US)","mac":"XX:XX:XX:XX:XX:XX","deviceId":"8006E0D62C90698C6A3EF72944F56DDC17D0DB80","hwId":"A0E3CC8F5C1166B27A16D56BE262A6D3","fwId":"DB4F3246CD85AA59CAE738A63E7B9C34","oemId":"4AFE44A41F868FD2340E6D1308D8551D","alias":"Christmas Tree Switch","dev_name":"Wi-Fi Smart Light Switch","icon_hash":"","relay_state":1,"on_time":9586,"active_mode":"schedule","feature":"TIM","updating":0,"rssi":-53,"led_off":0,"latitude":X,"longitude":-X}}}
INFO:root:Identify: <bound method SmartPlug.identify of <pyHS100.pyHS100.SmartPlug object at 0x76a1c710>>
DEBUG:pyHS100.pyHS100:> (31) {"system": {"get_sysinfo": {}}}
DEBUG:pyHS100.pyHS100:< (594) {"system":{"get_sysinfo":{"err_code":0,"sw_ver":"1.1.0 Build 160521 Rel.085826","hw_ver":"1.0","mic_type":"IOT.SMARTPLUGSWITCH","model":"HS200(US)","mac":"XX:XX:XX:XX:XX:XX","deviceId":"8006E0D62C90698C6A3EF72944F56DDC17D0DB80","hwId":"A0E3CC8F5C1166B27A16D56BE262A6D3","fwId":"DB4F3246CD85AA59CAE738A63E7B9C34","oemId":"4AFE44A41F868FD2340E6D1308D8551D","alias":"Christmas Tree Switch","dev_name":"Wi-Fi Smart Light Switch","icon_hash":"","relay_state":1,"on_time":9586,"active_mode":"schedule","feature":"TIM","updating":0,"rssi":-54,"led_off":0,"latitude":X,"longitude":-X}}}
INFO:root:Sysinfo: {'sw_ver': '1.1.0 Build 160521 Rel.085826', 'led_off': 0, 'hwId': 'A0E3CC8F5C1166B27A16D56BE262A6D3', 'hw_ver': '1.0', 'dev_name': 'Wi-Fi Smart Light Switch', 'deviceId': '8006E0D62C90698C6A3EF72944F56DDC17D0DB80', 'rssi': -54, 'longitude': -X, 'relay_state': 1, 'fwId': 'DB4F3246CD85AA59CAE738A63E7B9C34', 'mic_type': 'IOT.SMARTPLUGSWITCH', 'oemId': '4AFE44A41F868FD2340E6D1308D8551D', 'on_time': 9586, 'icon_hash': '', 'latitude': X, 'alias': 'Christmas Tree Switch', 'feature': 'TIM', 'mac': 'XX:XX:XX:XX:XX:XX', 'active_mode': 'schedule', 'updating': 0, 'model': 'HS200(US)'}`

HS110 Plug
`pi@pi:~/pyHS100 $ python3.4 -m examples.cli 10.0.0.12
DEBUG:pyHS100.pyHS100:> (31) {"system": {"get_sysinfo": {}}}
DEBUG:pyHS100.pyHS100:< (598) {"system":{"get_sysinfo":{"err_code":0,"sw_ver":"1.0.8 Build 151113 Rel.24658","hw_ver":"1.0","type":"IOT.SMARTPLUGSWITCH","model":"HS110(US)","mac":"XX:XX:XX:XX:XX:XX","deviceId":"800654F32938FCBA8F7327887A386476172B5B53","hwId":"60FF6B258734EA6880E186F8C96DDC61","fwId":"E16EB3E95DB6B47B5B72B3FD86FD1438","oemId":"FFF22CFF774A0B89F7624BFC6F50D5DE","alias":"Mobile Plug","dev_name":"Wi-Fi Smart Plug With Energy Monitoring","icon_hash":"","relay_state":1,"on_time":9022,"active_mode":"schedule","feature":"TIM:ENE","updating":0,"rssi":-61,"led_off":0,"latitude":X,"longitude":-X}}}
INFO:root:Identify: <bound method SmartPlug.identify of <pyHS100.pyHS100.SmartPlug object at 0x769ea710>>
DEBUG:pyHS100.pyHS100:> (31) {"system": {"get_sysinfo": {}}}
DEBUG:pyHS100.pyHS100:< (598) {"system":{"get_sysinfo":{"err_code":0,"sw_ver":"1.0.8 Build 151113 Rel.24658","hw_ver":"1.0","type":"IOT.SMARTPLUGSWITCH","model":"HS110(US)","mac":"XX:XX:XX:XX:XX:XX","deviceId":"800654F32938FCBA8F7327887A386476172B5B53","hwId":"60FF6B258734EA6880E186F8C96DDC61","fwId":"E16EB3E95DB6B47B5B72B3FD86FD1438","oemId":"FFF22CFF774A0B89F7624BFC6F50D5DE","alias":"Mobile Plug","dev_name":"Wi-Fi Smart Plug With Energy Monitoring","icon_hash":"","relay_state":1,"on_time":9022,"active_mode":"schedule","feature":"TIM:ENE","updating":0,"rssi":-64,"led_off":0,"latitude":X,"longitude":-X}}}
INFO:root:Sysinfo: {'on_time': 9022, 'type': 'IOT.SMARTPLUGSWITCH', 'fwId': 'E16EB3E95DB6B47B5B72B3FD86FD1438', 'updating': 0, 'hwId': '60FF6B258734EA6880E186F8C96DDC61', 'feature': 'TIM:ENE', 'sw_ver': '1.0.8 Build 151113 Rel.24658', 'oemId': 'FFF22CFF774A0B89F7624BFC6F50D5DE', 'rssi': -64, 'active_mode': 'schedule', 'hw_ver': '1.0', 'deviceId': '800654F32938FCBA8F7327887A386476172B5B53', 'longitude': -X, 'led_off': 0, 'dev_name': 'Wi-Fi Smart Plug With Energy Monitoring', 'latitude': X, 'model': 'HS110(US)', 'alias': 'Mobile Plug', 'mac': 'XX:XX:XX:XX:XX:XX', 'icon_hash': '', 'relay_state': 1}
INFO:root:== Emeter ==
DEBUG:pyHS100.pyHS100:> (32) {"emeter": {"get_realtime": {}}}
DEBUG:pyHS100.pyHS100:< (117) {"emeter":{"get_realtime":{"current":0.268587,"voltage":125.836131,"power":33.495623,"total":0.199000,"err_code":0}}}
INFO:root:- Current: {'power': 33.495623, 'current': 0.268587, 'voltage': 125.836131, 'total': 0.199}
INFO:root:== Monthly ==
DEBUG:pyHS100.pyHS100:> (45) {"emeter": {"get_monthstat": {"year": 2016}}}
DEBUG:pyHS100.pyHS100:< (144) {"emeter":{"get_monthstat":{"month_list":[{"year":2016,"month":11,"energy":1.089000},{"year":2016,"month":12,"energy":1.582000}],"err_code":0}}}
INFO:root:{11: 1.089, 12: 1.582}
INFO:root:== Daily ==
DEBUG:pyHS100.pyHS100:> (56) {"emeter": {"get_daystat": {"month": 11, "year": 2016}}}
DEBUG:pyHS100.pyHS100:< (418) {"emeter":{"get_daystat":{"day_list":[{"year":2016,"month":11,"day":24,"energy":0.026000},{"year":2016,"month":11,"day":25,"energy":0.109000},{"year":2016,"month":11,"day":26,"energy":0.109000},{"year":2016,"month":11,"day":27,"energy":0.130000},{"year":2016,"month":11,"day":28,"energy":0.216000},{"year":2016,"month":11,"day":29,"energy":0.319000},{"year":2016,"month":11,"day":30,"energy":0.180000}],"err_code":0}}}
INFO:root:{24: 0.026, 25: 0.109, 26: 0.109, 27: 0.13, 28: 0.216, 29: 0.319, 30: 0.18}`

**Comment by rytilahti** [comment]
@hoveeman looks fine to me, check out the README.md for details for controlling, the cli tool doesn't implement that currently. It's unknown whether the current master works with homeassistant at this point, but you should be able to turn it on and off from the console with a simple script.

**Comment by rytilahti** [comment]
Since there has been no updates I assume this has been fixed. Please reopen a new issue if it's still not working.
