### ISSUE TITLE
Power History

### ISSUE THREAD

**Issue by tutorialevideo** [GadgetReactor/pyHS100#148]
Hi,
One quick question how can i see la history of 24/h power consuption ? 
Do you have some recomandation for this?

**Comment by rytilahti** [comment]
Is `get_emeter_daily` what you are looking for: https://github.com/GadgetReactor/pyHS100/blob/master/pyHS100/smartdevice.py#L408 ?

**Comment by rytilahti** [comment]
Closing as stale, please reopen if this is still a problem.
