### ISSUE TITLE
Python Version Number

### ISSUE THREAD

**Issue by mcheavens** [GadgetReactor/pyHS100#149]
I am not a python coder, but I do see that it looks like the current version requires version 3 or 4 of python. But with version 2.7.12 when trying to run pyhs100 I get the following:

[root@3Igor-Cam-Srv /usr/local/bin] # pyhs100
Traceback (most recent call last):
  File "/usr/local/bin/pyhs100", line 7, in <module>
    from pyHS100.cli import cli
  File "/usr/local/lib/python2.7/dist-packages/pyHS100/__init__.py", line 16, in <module>
    from .smartdevice import SmartDevice, SmartDeviceException
  File "/usr/local/lib/python2.7/dist-packages/pyHS100/smartdevice.py", line 76
    host: str,
        ^
SyntaxError: invalid syntax

Here is what I can see in cli.py:
if sys.version_info < (3, 4):
    print("To use this script you need python 3.4 or newer! got %s" %
          sys.version_info)
    sys.exit(1)

**Comment by kirichkov** [comment]
Indeed, version 2 is no longer supported. You should use python 3.4 or later.
