### ISSUE TITLE
Static ip 

### ISSUE THREAD

**Issue by tutorialevideo** [GadgetReactor/pyHS100#155]
Hi,

Is there any option to setup a static ip on this smart plugs?

Thank you

**Comment by kirichkov** [comment]
I don't think this is a relevant to this library. You can configure your router to assign your plug a static DHCP lease which will have the same effect.

**Comment by rytilahti** [comment]
Just for future reference, I don't think there is a known API to do that, either, but if there were, support could definitely be added.
