### ISSUE TITLE
HS300 not listed in Discover.discover()

### ISSUE THREAD

**Issue by kevank** [GadgetReactor/pyHS100#167]
Using the following code:

```
from pyHS100 import Discover

for dev in Discover.discover().values():
        print(dev)
```

The output lists HS100s and HS105s but nothing from the HS300.

Running cli.py does list the HS300 during discovery.

**Comment by kevank** [comment]
Found out if I wait long enough it crashes with the linked error and traceback:
https://paste.tinyw.in/index.php/view/6abe9af6

**Comment by jimboca** [comment]
Yes, that issue is mentioned in #165, this should be closed.

**Comment by eode** [comment]
Agree, this issue should be closed.

**Comment by kirichkov** [comment]
Closing as duplicate of #165
