### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by Dhiyaddein** [GadgetReactor/pyHS100#171]
Hello. 
Before asking, I have to applaud everyone involved in this project for the job well done.
I do have one concern regarding the device knowing how simple this library works. I'm currently using HS110. How do I set the device with username and password or any authentication method to disallow the application to access the device not unless a password is supplied? 

Thanks in advance

**Comment by Benoss** [comment]
I think the HS110 has not security, anybody that can access your local network can control it.
You should ask TPlink how you can secure your device

**Comment by rytilahti** [comment]
Hi, and thanks for the compliments, I'm sure all contributors appreciate that. Now to your question, as @Benoss said, there is no security for local controls, so anyone inside your local network can control these devices. As there is nothing this library can do to fix this, I'm closing this.
