### ISSUE TITLE
HS105 support

### ISSUE THREAD

**Issue by trainman419** [GadgetReactor/pyHS100#18]
I've recently picked up an HS105 and I'd like to get it set up with HomeAssistant.

I tried adding it to my config following https://home-assistant.io/components/switch.tplink/ , but it hangs at `INFO:homeassistant.components.switch:Setting up switch.tplink`

Given https://community.home-assistant.io/t/compatibility-with-tp-link-smart-plugs/7005/3 , it sounds like there's probably some incompatibility with the HS105 .

I'm quite familiar with linux and python, but new in this area. What can I do to help debug?

**Comment by kirichkov** [comment]
Help will be much appreciated! I knew this model was in the works.

Can you run some commands so we can compare what this switch returns and see whether it's compatible with the HS100/110/200.

Can you clone this repository and run `examples/cli.py` and provide us with the end result?

Running nmap against the IP of the switch will also be useful, especially if running cli.py hangs or doesn't return anything.

Scan all ports using the command below:
`nmap -p 1-65535 IP_ADDRESS_OF_PLUG`

**Comment by trainman419** [comment]
When I run `examples/cli.py` it looks like it hangs waiting for a response from the HS105:

```
$ python3 examples/cli.py 192.168.1.105
DEBUG:pyHS100.protocol:> (31) {"system": {"get_sysinfo": {}}}
^CTraceback (most recent call last):
  File "examples/cli.py", line 15, in <module>
    logging.info("Identify: %s", hs.identify())
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 327, in identify
    return self.alias, self.model, self.features
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 365, in alias
    return self.sys_info['alias']
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 120, in sys_info
    self._fetch_sysinfo()
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 86, in _fetch_sysinfo
    self._sys_info = self.get_sysinfo()
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 176, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/home/hendrix/home/pyHS100/pyHS100/pyHS100.py", line 103, in _query_helper
    request={target: {cmd: arg}}
  File "/home/hendrix/home/pyHS100/pyHS100/protocol.py", line 49, in query
    chunk = sock.recv(4096)
KeyboardInterrupt
```

And while that is happening, I see the following exchange in tcpdump:

```
20:28:48.057061 IP bowbell.trainman.homelinux.net.35434 > HS105.trainman.homelinux.net.9999: Flags [S], seq 550559721, win 29200, options [mss 1460,sackOK,TS val 103218260 ecr 0,nop,wscale 7], length 0
20:28:48.093384 IP HS105.trainman.homelinux.net.9999 > bowbell.trainman.homelinux.net.35434: Flags [S.], seq 7823494, ack 550559722, win 1452, options [mss 1452], length 0
20:28:48.093442 IP bowbell.trainman.homelinux.net.35434 > HS105.trainman.homelinux.net.9999: Flags [.], ack 1, win 29200, length 0
20:28:48.093694 IP bowbell.trainman.homelinux.net.35434 > HS105.trainman.homelinux.net.9999: Flags [P.], seq 1:36, ack 1, win 29200, length 35
20:28:48.135199 IP HS105.trainman.homelinux.net.9999 > bowbell.trainman.homelinux.net.35434: Flags [.], ack 1, win 4356, length 0
20:28:48.584415 IP bowbell.trainman.homelinux.net.35434 > HS105.trainman.homelinux.net.9999: Flags [P.], seq 1:36, ack 1, win 29200, length 35
20:28:48.623419 IP HS105.trainman.homelinux.net.9999 > bowbell.trainman.homelinux.net.35434: Flags [.], ack 36, win 4356, length 0
```
(ctrl-C)
```
20:31:54.593695 IP bowbell.trainman.homelinux.net.35434 > HS105.trainman.homelinux.net.9999: Flags [F.], seq 36, ack 1, win 29200, length 0
20:31:54.634170 IP HS105.trainman.homelinux.net.9999 > bowbell.trainman.homelinux.net.35434: Flags [.], ack 37, win 4356, length 0
20:31:54.683428 IP HS105.trainman.homelinux.net.9999 > bowbell.trainman.homelinux.net.35434: Flags [F.], seq 1, ack 37, win 4356, length 0
20:31:54.683467 IP bowbell.trainman.homelinux.net.35434 > HS105.trainman.homelinux.net.9999: Flags [.], ack 2, win 29200, length 0
```

The second packet exchange looks like a pretty typical TCP socket teardown, but the first exchange looks like the HS105 is responding to the query with a 0-length packet.

I added a timeout so that the example doesn't hang forever in #19.

**Comment by trainman419** [comment]
The full port scan took a while, and still only shows port 9999 as open:

```
$ sudo nmap -p1-65535 192.168.1.105
[sudo] password for hendrix: 

Starting Nmap 6.40 ( http://nmap.org ) at 2016-12-16 20:04 PST
^[3Nmap scan report for HS105.trainman.homelinux.net (192.168.1.105)
Host is up (0.037s latency).
Not shown: 65534 filtered ports
PORT     STATE SERVICE
9999/tcp open  abyss
MAC Address: 50:C7:BF:11:24:A8 (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 5057.60 seconds
```

**Comment by kirichkov** [comment]
OK. It's using the same port as HS100/110/200.

Can you run the following script from Python and paste the result:
```python
from pyHS100 import SmartPlug
smartplug = SmartPlug('IP_OF_SWITCH')
smartplug._fetch_sysinfo
smartplug._sys_info
```

I'm using the current master of pyHS100. Older versions of the module, including the one used in home assistant, have slightly different syntax.

**Comment by rytilahti** [comment]
@kirichkov examples/cli.py calls already sys_info() and it seems to stall while reading from the socket, so for some reason the plug isn't answering.

@trainman419 has the plug been connected with the official app already? Is the connectivity working there? Can you get a traffic dump from port 9999 tcp & udp?

If you are on the same network with the plug, you could also try out https://github.com/rytilahti/pyHS100/tree/discover - just checkout and:
```python -m examples.discover```

**Comment by InblEric** [comment]
Any update on this issue? I'm having the same problem.

**Comment by kirichkov** [comment]
No update because none of the developers has HS105. If you have some coding background and HS105 you can assist with testing code. If no one steps up support can't happen.

**Comment by trainman419** [comment]
The plug definitely works with the iPhone and Android apps.

I did some disassembling of the android app (as suggested by one of the original HS100 reverse-engineering posts) and found that it seems to be using the same "encryption", but there also appears to be some additional code for the HS105 that don't exist for the HS100 and the HS110.

The library is definitely hanging in waiting for the first packet back from the device, so I don't think there's much that I can learn by debugging the python library further.

My network is WPA encrypted by default, and I think it's using per-client keys, so it's not easy to sniff the traffic between the App and the plug. I think my next step is going to be to set up an unencrypted network and sniff the traffic there, and then I suspect I'll be able to put the captured packets through the existing HS100 decryptor and see how they're different. Unfortunately that's a few hours of setup and capture time, and I've been on vacation and haven't had time to get to it.

**Comment by kirichkov** [comment]
My wild guess is that they've changed the encryption key. If you manage to sniff the traffic between the app and the plug, check the data being exchanged against the hex strings in this commit - https://github.com/GadgetReactor/pyHS100/blob/ef85f939fd5b07064a0f34dfa673fa7d6140bd95/pyHS100/pyHS100.py

If the code is the same, then the encryption key is the same, only the protocol is changed. If you're seeing different data it could be different protocol and/or encryption key.

You should be able to sniff the wireless traffic using a regular sniffer like wireshark, and putting your wi-fi interface in promiscuous mode, as long as you are using WPA PSK (Pre-shared key, i.e. the same password is used to connect to the network on all devices) and not WPA Enterprise.

**Comment by InblEric** [comment]
If I get some free time I can try to dig into the code a bit. 

~~My TP-Link iOS app works, but using pyHS100 I can't connect to the socket for some reason.~~

I was able to get the connection working, but the response taken in by the decrypt method in protocol.py is empty, so I think it's not responding to the message so it may be encrypted improperly. I think my next step would be sniffing the traffic between the plug and my machine but that's about where my knowledge ends. I can try to teach myself some of that stuff. 

To be more clear, I actually "get" a response and attempt to load it into JSON and that's where it fails.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyHS100/pyHS100.py", line 86, in _fetch_sysinfo
    self._sys_info = self.get_sysinfo()
  File "pyHS100/pyHS100.py", line 177, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "pyHS100/pyHS100.py", line 107, in _query_helper
    raise SmartPlugException(ex)
pyHS100.pyHS100.SmartPlugException: No JSON object could be decoded
```

I believe the exception is initially thrown here:

https://github.com/GadgetReactor/pyHS100/blob/master/pyHS100/protocol.py#L60

**Comment by rytilahti** [comment]
@kirichkov I doubt they changed the encryption, as that'd require second round for detecting both types of plugs.

@InblEric Try and enable debug logging or modify the _LOGGER.debug() just above to _LOGGER.error() to see what is being decoded. Maybe something happened to those four bytes that are stripped out before.. :-) The original problem may be different or then not, but it looks like you are receiving something there, so debug log would be useful.

**Comment by InblEric** [comment]
I got 

`No handlers could be found for logger "pyHS100.protocol"`

**Comment by rytilahti** [comment]
How are you running it? From your own script? Try
```bash
python3 -m examples.cli <ip address>
```
inside the source root.

**Comment by InblEric** [comment]
I was just instantiating the plug and doing

`smartplug._fetch_sysinfo()`

When I run cli.py I get this (it looks the same whether I use _LOGGER.debug or _LOGGER.error):

```
DEBUG:pyHS100.protocol:> (31) {"system": {"get_sysinfo": {}}}
ERROR:pyHS100.protocol:< (0) 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/json/decoder.py", line 367, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Developer/HS100/pyHS100/pyHS100/pyHS100.py", line 103, in _query_helper
    request={target: {cmd: arg}}
  File "/Developer/HS100/pyHS100/pyHS100/protocol.py", line 70, in query
    return json.loads(response)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/json/__init__.py", line 316, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/json/decoder.py", line 351, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/json/decoder.py", line 369, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "cli.py", line 15, in <module>
    logging.info("Identify: %s", hs.identify())
  File "/Developer/HS100/pyHS100/pyHS100/pyHS100.py", line 328, in identify
    return self.alias, self.model, self.features
  File "/Developer/HS100/pyHS100/pyHS100/pyHS100.py", line 366, in alias
    return self.sys_info['alias']
  File "/Developer/HS100/pyHS100/pyHS100/pyHS100.py", line 121, in sys_info
    self._fetch_sysinfo()
  File "/Developer/HS100/pyHS100/pyHS100/pyHS100.py", line 86, in _fetch_sysinfo
    self._sys_info = self.get_sysinfo()
  File "/Developer/HS100/pyHS100/pyHS100/pyHS100.py", line 177, in get_sysinfo
    return self._query_helper("system", "get_sysinfo")
  File "/Developer/HS100/pyHS100/pyHS100/pyHS100.py", line 107, in _query_helper
    raise SmartPlugException(ex)
pyHS100.pyHS100.SmartPlugException: No JSON object could be decoded
```

**Comment by rytilahti** [comment]
Ah, sorry, missed the 0-length packet there. We should handle that gracefully, but looks like there are no other packets received according to that earlier tcpdump.

Assuming you are on the same subnet, you could try out the discover script from discover branch over here: https://github.com/rytilahti/pyHS100/tree/discover -- during my tests I'm not able to receive the data, although tcpdump was showing that the plug is responsive to that request.

Another possibility is to use the kasa app & tap on wifi to capture how it's communicating with the device. For decrypting the raw payloads you can use the decrypt() in pyHS100/protocol.py .

**Comment by InblEric** [comment]
Awesome! I have to get to sleep but I'll try both of these out tomorrow.

**Comment by rytilahti** [comment]
There's now discovery mode & example script in that branch, or available from pull #25. To try it out, just run ```python3 -m examples.discover```.

**Comment by InblEric** [comment]
I was able to discover the device, any particular data I should be looking for? @rytilahti

**Comment by trainman419** [comment]
I was finally able to capture a packet dump of the communication between my phone and my HS105, and I'm digging through it now to try to understand the protocol.

So far I've confirmed that they haven't changed the "encryption" or the initialization value, so the decoder still works.

I've also found that my HS105 is sending UDP packets with it's state; I'm not sure the older plugs did that.

I also see that the first 4 bytes of each TCP payload are populated with the packet length. I've tried adding that to the library, but either I have it wrong or it isn't helping.

**Comment by trainman419** [comment]
More poking, and I've discovered a few more things:
1) the HS105 works much better when it's on the same network as my dev machine (silly me)
2) the HS105 seems to require that the first four bytes of the TCP message be set to the payload size (previously it was zero)
3) My timeout code was interacting poorly with the receive logic and seemed to be causing a timeout on every receive.
4) the HS105 seems to respond better to UDP requests than it does to TCP requests.
5) In my packet dumps it seems like the HS105 has to do some TCP retransmissions before it works out the window size, and that seems to interact with the Linux TCP stack in a way that causes a multi-second delay. (or maybe that delay is something else I'm not doing quite right)

**Comment by trainman419** [comment]
My changes are nowhere near ready for review, but for anyone who is interested my changes (and my pcap decoder) are in [this commit](https://github.com/trainman419/pyHS100/commit/ab6050e0efc92d9d7c97129bd46c48176ba8bb20).

**Comment by kirichkov** [comment]
Regarding the UDP notifications - this is new! I read the app was querying the plug every 2 seconds for HS100/110. I haven't personally confirmed it.

**Comment by rytilahti** [comment]
@InblEric mind posting the output showing the sysinfo after masking the identifiers?

@trainman419: is it doing udp broadcasting? if so, yeah, works only on the same network (similarly to discover).

**Comment by InblEric** [comment]
@rytilahti 

```{'ip': 'x.x.x.x',
 'port': 9999,
 'sys_info': {'emeter': {'err_code': -1, 'err_msg': 'module not support'},
              'system': {'get_sysinfo': {'active_mode': 'none',
                                         'alias': 'MiniPlug',
                                         'dev_name': 'Smart Wi-Fi Plug Mini',
                                         'deviceId': '<id>',
                                         'err_code': 0,
                                         'feature': 'TIM',
                                         'fwId': '<fwid>',
                                         'hwId': '<hwid>',
                                         'hw_ver': '1.0',
                                         'icon_hash': '',
                                         'latitude_i': 0,
                                         'led_off': 0,
                                         'longitude_i': 0,
                                         'mac': '<mac>',
                                         'model': 'HS105(US)',
                                         'oemId': '<oem>',
                                         'on_time': 0,
                                         'relay_state': 0,
                                         'rssi': -31,
                                         'sw_ver': '1.0.6 Build 160722 Rel.081616',
                                         'type': 'IOT.SMARTPLUGSWITCH',
                                         'updating': 0}}}```

**Comment by trainman419** [comment]
@rytilahti I'm testing by sending UDP packets with the request, and the response is a unicast packet. I think this is different from discovery, and I suspect it would work across network boundaries.

**Comment by rytilahti** [comment]
@InblEric thanks, looks similar to the others (except latitude_i/longitude_i instead of latitude/longitued). One thing different is active_mode not being "schedule" like usually.. 

@trainman419 ok, nice. Let's know / make a patch when you have figured things out or need any help. I can't really do much without having such a plug, and I think the same applies to other recently active devs..

**Comment by mjg59** [comment]
Ha, I actually figured the same stuff out as part of https://github.com/GadgetReactor/pyHS100/pull/30 - can you let me know if the HS105 works with that branch?

**Comment by InblEric** [comment]
@rytilahti @mjg59 Is this something I could test out with my HS105 to see if it works? I saw someone in #30 asking @trainman419 to test it out on his.

**Comment by rytilahti** [comment]
@InblEric yes, testing the PR against HS105 would be appreciated, as it implements the changed protocol.

**Comment by InblEric** [comment]
@rytilahti Great I'll try to do that ASAP. Might not have time today but I'll try to get it tested within the next couple days.

**Comment by InblEric** [comment]
@rytilahti @mjg59 

![It's working!](http://i.imgur.com/tHEQsOH.gif)

I checked out the branch for PR #30 and ran the example code from the README, tested that I could turn the plug off and back on. Seems to be working properly.

**Comment by trainman419** [comment]
I've confirmed that this works with my HS105 too.

**Comment by jpflanigan** [comment]
Have the pyHS100 updates been incorporated into Home-Assistant 0.39.1?  My HS-105 isn't found and the .log file fills with errors about this switch.   

If not, is there a way to update just the pyHS100 component of hass?

**Comment by kirichkov** [comment]
They are not incorporated. To update you'd need to adjust the hass component code

**Comment by andyat** [comment]
Any updates on when HS105 support will be released in HA?

**Comment by mweinelt** [comment]
@rytilahti was planning do to another release of pyhs100 this weekend, so maybe we land an upgraded binding in 0.41. I don't believe it's much more than upgrading the dependency, but someone needs to handle that.

**Comment by jaytea33** [comment]
0.41 is supposedly being released later today.  *fingers crossed* for HS105 support

**Comment by jpflanigan** [comment]
@jaytea33, I've been watching this for a while and I think we'll have to wait for the first Home-Assistant update AFTER the next pyHS100 update.  Looks like pyHS100 team is working towards 0.2.4 which AFAIK would be the first to contain the HS105 discovery fix.  

Even then I don't know if HA automatically pulls the latest components or if someone on the HA team has to validate before inclusion...

In either case huge respect and gratitude to all who advance these open source projects!

**Comment by rytilahti** [comment]
I just published a new release which incorporates the required patches. Home assistant uses version pinning so this will be available first after this gets merged: https://github.com/home-assistant/home-assistant/pull/6790

In the meanwhile it is however possible to install the newest release manually. Please do test and report back, it'd be nice to know that everything is working correctly before the updated version gets included into homeassistant. The newly added pyhs100 console tool allows easy discovery and testing of functionality, please try it out :)

**Comment by jpflanigan** [comment]
I'm a github noob with an HS105 and am willing to try the new release if someone can provide a starting point...google was unhelpful in searching how to manually update a single component of HA.  I tried a few weeks ago to copy the latest pyHS100 files into the deps  folder and borked my rasp pi setup and had to start over with a fresh install (saved the .yaml etc. but still a multi-hour waste of time).

Is it as simple as:  
pip3 install --upgrade homeassistant
or
pip3 install --upgrade pyHS100
from within the proper virtual environment?

**Comment by kirichkov** [comment]
The correct way for either venv and stand alone would be:

    pip3 install pyHS100==0.2.4 --upgrade --target /home/hass/.homeassistant/deps

Given that your home assistant configuration folder is `/home/hass/.homeassistant`. However keep in mind that sometimes modules introduce breaking changes in their API, which means this type of upgrade will simply brake the hass component, instead of bring in the new features!

**Comment by jpflanigan** [comment]
I did the manual upgrade as @kirichkov described...adjusting the config folder per my setup and the version to pyHS100==0.2.4.1  

It worked!  I initially gained control of HS105 and lost control of two HS100's.  

I was able to use the "pyhs100 discover" to do some troubleshooting.  For some reason, the HS100's were not found.  Even pinging the IP addresses of the HS100's yielded no reply...a rasp pi reboot and power-cycling the HS100's seemed to get everyone talking again.  They may have come back on their own, but I wasn't patient enough to wait ;-)

Thanks for the help!  I'll keep fingers crossed that all survives the next HA update.

**Comment by jaytea33** [comment]
YES!  Confirmed working with my HS105 as well; I can finally control it with my Google Home.  Ran into some issues like missing future.utils and stuff, and my HTTP server was denied permissions.  Used a Ubuntu virtual machine and finally got it working.  Thanks to anyone who worked on this.
