### ISSUE TITLE
import failure

### ISSUE THREAD

**Issue by Andymator21** [GadgetReactor/pyHS100#190]
Hello
Im sure my problem is due to me lacking experience. What I want to achieve in the end is being able to turn my HS100 on and off - so that I can get my 96 students to do the same with their RPis and smart plugs.

I have just used git clone to install pyHS100 to my RPi3b+. I can see that the folders and files are there. I start my coding-program thonny and try to import smartplug:
![image](https://user-images.githubusercontent.com/57047693/71509304-284e3280-288b-11ea-8d78-53094b2638fa.png)

The error I get seems to come from smartdevice.py, not finding the module depreciation.
![image](https://user-images.githubusercontent.com/57047693/71509411-75ca9f80-288b-11ea-9d70-ab1139d3fde7.png)

Do you have any idea about what kind of stupid mistake I have made?

**Comment by rytilahti** [comment]
For regular installation (when you don't want to modify anything in the library itself), you should be installing it from pypi:
```
pip install pyhs100
```
Then the correct import line would be `from pyHS100 import SmartPlug`. The error you are seeing is coming from the missing dependency of `deprecation` lib (which you could install manually with pip if you prefer to do so).

**Comment by Andymator21** [comment]
Thanks! It works now. Im super happy!

**Comment by Andymator21** [comment]
In the smartplug.py, I dont see a method for getting the emeter values, only the method "has_emeter". Can you tell me how I can get the emeter values from my python code? Is it possible?

**Comment by rytilahti** [comment]
Glad to hear it's working! The common functionalities for different device types (plugs, bulbs, ..) are in the parent class (`SmartDevice`), here are the emeter methods: https://github.com/GadgetReactor/pyHS100/blob/master/pyHS100/smartdevice.py#L440

**Comment by Andymator21** [comment]
Works great. That you for your fast replies!
