### ISSUE TITLE
TP-link KP200 not working proper  NOT A DUPLICATE OF ADD SUPPORT FOR THE KP200 

### ISSUE THREAD

**Issue by trentjw** [GadgetReactor/pyHS100#191]
**Home Assistant release with the issue:**
103.4

**Last working Home Assistant release (if known):**
unkown

**Operating environment (Hass.io/Docker/Windows/etc.):**
venv on raspberry

**Integration:**
TP-Link

**Description of problem:**
KP200 not reporting status just shows off not showing both switches for the plug both come on with switch on HA then switch slides back to off even with plug turned on can turn on plug via switch and quicky slid to off to power off switch

**Also will not auto discover tp-link devices, I  had to manually add TP-Link and add IP of switches in config file. The HS200 is working fine and reports as it should, the KP200 is not only shows it is off, it shows unavailable if I disconnect  the power to it, so it kind of talks to HA**

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
```yaml

```

**Traceback (if applicable):**
```

```

**Additional information:**
KP200 Firmware: 1.0.7 Build 190309 Rel.180427

**Comment by rytilahti** [comment]
This is a homeassistant issue. Please reopen with more details if it is not working using the command line tool, thanks!
