### ISSUE TITLE
Smart Bulb KL50

### ISSUE THREAD

**Issue by Pel1can111** [GadgetReactor/pyHS100#192]
Does anyone know if this bulb will work? 

I was looking at adding smart bulbs to my home and didn't want to buy some if I have to use their app :)

I'd be happy to buy some to test if it would help getting them added.

Great work on adding the power strip

**Comment by rytilahti** [comment]
Looks like it is using the kasa app, so it should work directly. If not, please feel free to re-open the issue :-)

**Comment by Pel1can111** [comment]
Thanks for the reply. I was just about to reply. I took the risk and grabbed some anyway and they work perfectly in case anyone else finds this.

**Comment by rytilahti** [comment]
Great! Do you mind installing https://github.com/python-kasa/python-kasa from git master, running `kasa dump-discover` and creating a PR similar to this: https://github.com/python-kasa/python-kasa/pull/25?
