### ISSUE TITLE
Get rid of click-datetime dep

### ISSUE THREAD

**Issue by ggardet** [GadgetReactor/pyHS100#194]
`click-datetime` from https://github.com/click-contrib/click-datetime is outdated, unmaintained and has no license. 
This would be better to get rid of this dependence.

**Comment by rytilahti** [comment]
Take a look at https://github.com/python-kasa/python-kasa/ which is an asyncio fork of this project, it has been converted to use click's built-in datetime. There has been no releases so far, but hopefully that will change soon.

**Comment by ggardet** [comment]
Thanks, python-kasa looks good.
