### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by mweinelt** [GadgetReactor/pyHS100#195]
And link prominently to the new one.

**Comment by sofiadutta** [comment]
Can you please provide the link to the new one?

**Comment by rytilahti** [comment]
It is still waiting for the first release, there are still some steps to take to make that happen. It will be announced after it's ready for the prime time though :-) The link is https://github.com/python-kasa/python-kasa

**Comment by rytilahti** [comment]
I just did close all the PRs and issues, the README needs still to be updated.
