### ISSUE TITLE
python AttributeError: 'module' object has no attribute 'inet_pton'

### ISSUE THREAD

**Issue by strunker** [GadgetReactor/pyHS100#21]
Windows 10 py 2.7

Worked around this issue by running below from cmd, then in pyHS100.py I added import win_inet_pton, at top of code body on line 23.

pip install win_inet_pton

you may want to get this install going via pip, and mark win_inet_pton as a dependency for windows machines... It isnt necessary on mac os \ linux

**Comment by strunker** [comment]
May have spoken to soon. I dont get errors on object creation now as I was prior, but it doesnt really seem to be doing much, turn on commands\off are not behaving as expected. No exceptions are being raised, just nothing is actually happening.

**Comment by strunker** [comment]
It is working to a certain extent. as I can query for info so thats a positive. 

{u'oemId': u'37589AA1F5CACDC53E2914B7760127E5', u'dev_name': u'Wi-Fi Smart Plug', u'on_time': 101, u'feature': u'TIM', u'fwId': u'6FF450BEEA362AD5C1510481FABABD86', u'icon_hash': u'', u'relay_state': 1, , u'hw_ver': u'1.0', u'type': u'IOT.SMARTPLUGSWITCH', u'led_off': 0, u'hwId': u'5EACBE93FB9E32ECBE1F1C2ADE6DDE11', u'sw_ver': u'1.1.0 Build 160503 Rel.144239',u'active_mode': u'schedule', u'deviceId': u'8006EC981D50F56F2B6323BA150DF5B917B7DFA1', u'updating': 0, u' u'alias': u'Kitchen', u'rssi': -64, u'model': u'HS100(US)'}

**Comment by strunker** [comment]
only other notable error is the below. not entirely sure what to make of that.  

Traceback (most recent call last):
  File "C:\Python27\Lib\site-packages\pyHS100-0.2.2-py2.7.egg\pyHS100\pyHS100.py", line 25, in <module>
    from pyHS100.protocol import TPLinkSmartHomeProtocol
  File "C:\Python27\Lib\site-packages\pyHS100-0.2.2-py2.7.egg\pyHS100\pyHS100.py", line 25, in <module>
    from pyHS100.protocol import TPLinkSmartHomeProtocol
ImportError: No module named protocol
[Finished in 0.1s with exit code 1]

**Comment by rytilahti** [comment]
Do you have protocol.py inside pyHS100 dir? I'm unsure if this is python2 or windows problem itself, neither of them are thoroughly tested. Do you mind trying if it works with python3?

**Comment by rytilahti** [comment]
Closing for the lack of input. Please reopen if this is still an issue.

**Comment by anotherCogInGear** [comment]
Installed this package with pip, when I try to run pyHS100 with python 3 I get the exact same error even when I launch it from within the pyhs100 dir.
