### ISSUE TITLE
Home Assistant Integration?

### ISSUE THREAD

**Issue by rosahas** [GadgetReactor/pyHS100#27]
Has anyone tried to integrate this with Home Assistant?  If so, can you please post your configuration file?

**Comment by kirichkov** [comment]
This is  used in a home assistant component. The required configuration is in the documentation on HASS' website: https://home-assistant.io/components/switch.tplink/

**Comment by rosahas** [comment]
Can you please share the configuration file?  I have the TP link switch working already, but was looking to fix the problem of not being able to track switch state of the state changes using the physical button.

Thx

**Comment by kirichkov** [comment]
Unfortunately you cannot resolve the issue with a simple configuration entry.
Right now this can be resolved only by reverting to a previous version of home assistant. I see that improvements have been merged and I'll work on a pull request, but you'd have to wait for a new release of home assistant which will resolve the issue.

**Comment by rosahas** [comment]
Got it, thank you.

**Comment by rosahas** [comment]
Did this get resolved in the latest update? .36.1?  I haven't seen any changes

**Comment by kirichkov** [comment]
Already in 0.36
