### ISSUE TITLE
Upload releases to PyPI

### ISSUE THREAD

**Issue by rytilahti** [GadgetReactor/pyHS100#29]
Uploading the releases to PyPI will make it easier for users to install the package: https://packaging.python.org/distributing/#uploading-your-project-to-pypi

**Comment by rytilahti** [comment]
Done here, updated dependency on homeassistant for it: https://pypi.python.org/pypi/pyHS100

@GadgetReactor Please let me know your pypi user and I can transfer permissions on pypi.

**Comment by GadgetReactor** [comment]
thanks - i don't have a pypi account, would appreciate if you can help maintain it :)

**Comment by rytilahti** [comment]
Sure thing, I can do releases after release tags are there.
