### ISSUE TITLE
Exception timed out / protocol.py, line 99, in discover

### ISSUE THREAD

**Issue by oldfox94** [GadgetReactor/pyHS100#33]
Hello,
i've got an exception by calling the discover.py
See attached screenshot.
After the "socket.timeout: timed out" line it showes the results...

Sry for my short request, this is my first Issue submit in GitHub. :)

![grafik](https://cloud.githubusercontent.com/assets/15803918/21996856/839f96aa-dc2c-11e6-8b8e-ddb03b6fc73b.png)

**Comment by rytilahti** [comment]
Thanks for the report. #34 fixes this.
