### ISSUE TITLE
Running problems Win 7 Idle 2.7.3

### ISSUE THREAD

**Issue by Bazs87** [GadgetReactor/pyHS100#35]
Hi!

I have already installed python2.7 idle with setuptools, python-future-master, python-geoip-master
What do you think, how can I fix this problems?

I had this problems in first test: 
![Uploading github.jpg…]()

**Comment by Bazs87** [comment]
![github](https://cloud.githubusercontent.com/assets/25537789/22608516/823786d0-ea5d-11e6-9f17-74f681a6742e.jpg)

**Comment by rytilahti** [comment]
The easiest solution is just to use python3, I think we should not even try to support python2 actually.

**Comment by Bazs87** [comment]
OK.
I need to python only becouse of your development, I need to this great function.
Can you tell me exactly witch IDLE version, lib version recommend? What I need to install?
I have basic experience with python, I didn't work until now with libs/modules.
Thank you!

**Comment by rytilahti** [comment]
What are you trying to achieve? Anyway, you should upgrade to the newest version, the console tool can be used to verify that your setup is working accordingly. Then you can go and use the library as shown in README. For using Python modules in general you should consult Python's documentation and/or tutorials found via search engine, there is nothing really special in this module compared to others.

**Comment by rytilahti** [comment]
I'm closing this because there has been no input how we can help. Please reopen if this is still a problem, thanks!
