### ISSUE TITLE
This module would also support the HS200 wall switch if you would include it in models.

### ISSUE THREAD

**Issue by smaggard** [GadgetReactor/pyHS100#4]
I modified the latest code locally on my home assistant server and it worked perfectly with a hs200 wall switch.  It works exactly as an HS100 switch

def _identify_model(self):
        """Query sysinfo and determine model"""
        sys_info = self.get_info()

```
    if sys_info["system"]["get_sysinfo"]["model"][:5] == 'HS100':
        model = 100
    elif sys_info["system"]["get_sysinfo"]["model"][:5] == 'HS200':
        model = 100
    elif sys_info["system"]["get_sysinfo"]["model"][:5] == 'HS110':
        model = 110

    return model
```

**Comment by smaggard** [comment]
I have a branch created with full addition of the HS200 switch if you could a add me as a contributor.

**Comment by smaggard** [comment]
Code changes I am proposing can be found in https://github.com/smaggard/pyHS100/blob/master/pyHS100.py

**Comment by GadgetReactor** [comment]
That's great.

Please start a new branch, raise a pull request and we will be able to
check and merge it in.

**Comment by smaggard** [comment]
I have a new branch but I can't publish it

**Comment by smaggard** [comment]
I am getting the following error trying to create a branch, I think I need some permissions set.

You may not have permission to access pyHS100. Check Preferences to make sure you’re still logged in.

**Comment by smaggard** [comment]
I tried doing a pull request and got a permission denied that route too, let me know when you get the permissions setup.

**Comment by GadgetReactor** [comment]
Hi, there isn't any permissions. You won't be able to publish directly. Please see how to below, it's the same guidelines as used by Home-Assistant. 

## How to contribute

### If doing this for the first time

Fork this repo using the Fork button.
Clone your fork on your computer.

git clone https://github.com/YOUR_GITHUB_USERNAME/pyHS100.git
Add the main repo as upstream.

cd pyHS100
git remote add upstream https://github.com/gadgetreactor/pyHS100.git

### Every time

Be sure to always work with the current upstream master.

### Run this from your feature branch

git fetch upstream master  # to pull the latest changes into a local branch
git rebase upstream/master # to put those changes into your feature branch before your changes
Create a feature branch for your changes. This is important - don't push to master!

git checkout -b new-feature
Also, do a special branch based on your master for each feature you want to implement - don't put multiple features into one branch - this is also very important!

Do your work here and commit it. If there is an issue in the tracker that regards your commits, always reference it in the commit message. For example git commit -m "docs: add referencing issues (#2)".

Push this new branch into your fork.

git push origin new-feature
Open a pull request using GitHub.

**Comment by GadgetReactor** [comment]
Just some quick thoughts:

The identify_model was added in the last pull request. I think it should be more generic. This will allow other TP-Link devices to work if they follow a similar format. This is the main reason why the HS200 was no longer working after the latest update.

```
    def _identify_model(self):
        """Query sysinfo and determine model"""
        sys_info = self.get_info()
        model = sys_info["system"]["get_sysinfo"]["model"][:5]

        return model
```

For the lines with the following:

```
        if self.model == 100 or self.model == 200:
            return False
```

I would suggest to change it to:

```
    if self.model != "HS110":
       return False

```

**Comment by smaggard** [comment]
Done, thanks for giving me the steps.
