### ISSUE TITLE
Does not work with HS105

### ISSUE THREAD

**Issue by misiek303** [GadgetReactor/pyHS100#44]
Works great with HS100 and HS200.

I think is timing out when trying to get a plug state.

**Comment by misiek303** [comment]
I take it back, it works just fine. Some reason it goes offline.

**Comment by kirichkov** [comment]
What do you mean "goes offline"? After a while it doesn't receive commands?

If so - we've discussed this issue in #3 . My presumption is this is caused by voltage drops and besides fixing your electricity there's nothing that can be done about it.

**Comment by misiek303** [comment]
I wish I could tell it more details. But I connected it for the first time, configured through Kasa and then tried to use via your lib. I could not get status or turn off or on via your lib while I could via Kasa. Then it stopped working even in Kasa. I re-connected the plug, detach my lamp from it, and magically worked using your lib. Still works after 24h. So I really don't know what was the issue. I closed the subject. 

---
Since I am here I would like to show you how I use your software. I have Raspberry Pi as a home controller ( & model ), that collects status from all smart devices that runs schedules, keep stats and logs etc. I wrote QT phone app that behaves like a View, gets the data via socket & http requests. I attached some screenshots.

Thank you for your work !!!
![screenshot_20170323-173552](https://cloud.githubusercontent.com/assets/371344/24273280/6f82c6fa-0fef-11e7-955f-61bd976ef578.png)
![screenshot_20170323-173530](https://cloud.githubusercontent.com/assets/371344/24273281/6f92654c-0fef-11e7-90f3-19740e93e90b.png)
![screenshot_20170323-173256](https://cloud.githubusercontent.com/assets/371344/24273282/6f92e102-0fef-11e7-920e-33d11f1e0830.png)

**Comment by kirichkov** [comment]
What you've done looks quite nice! Any reason why not use something readily available ( home-assistant.io for example)?

As to the issues - this is pretty similar to what we are experiencing and describing in the aforementioned issue. Once the voltage is stable - it works for months.
