### ISSUE TITLE
HS100 UK Version does not respond to switch off

### ISSUE THREAD

**Issue by chrysnik** [GadgetReactor/pyHS100#45]
When setting the slider to on for any of the TP Link switches it switches to ON. After a while the slider moves automatically to off and the switch remains open. 
Trying again has no effect to the state of the switch - it remains open. 

Terminal (OS X) sends the following: 
17-04-06 00:17:33 WARNING (<concurrent.futures.thread.ThreadPoolExecutor object at 0x103c15be0>_9) [homeassistant.components.switch.tplink] Could not read state for Main Reading Light: [Errno 57] Socket is not connected

**Comment by rytilahti** [comment]
Could you try with the pyhs100 tool to see if you can connect to it at all? If yes and that seems to be working, this is a bug in the homeassistant component.

**Comment by chrysnik** [comment]
Hi Rytilahti. Can you point me to the pyhs100 tool?

**Comment by mweinelt** [comment]
It's part of the pyHS100 package.

Check out the README: https://github.com/GadgetReactor/pyHS100#discovering-devices

**Comment by rytilahti** [comment]
Please reopen if this is still an issue.
