### ISSUE TITLE
Upgrading from 0.2.3 to 0.2.4.1 breaks the switch functionality in HASS

### ISSUE THREAD

**Issue by chairstacker** [GadgetReactor/pyHS100#46]
While V0.2.3 works fine in HASS V0.2.4.1 stops an otherwise functioning config from working in HASS.
Simply upgrading pyHS100 is enough to stop it working.

Do I need o include more details, e.g. error messages on HASS, etc.?

**Comment by rytilahti** [comment]
Yes you need to include more info. I'm using pyHS100==0.2.4.1 with homeassistant from git and it's working here just fine.

Please adjust your homeassistant's logger to get more information:
```
logger:
  logs:
    pyHS100: debug
```

and check the log.

**Comment by chairstacker** [comment]
Thanks - very noob-ish question here:  where would I find the log :-S

And: after I run this:
`pip3 install --upgrade ./pyHS100/ --target ~/.homeassistant/deps`

I cannot even access my HASS frontend, although I can see that hass itself is running:
```
(homeassistant) homeassistant@GerstMeyersPi4:~$ sudo systemctl status home-assistant@homeassistant -l
● home-assistant@homeassistant.service - Home Assistant
   Loaded: loaded (/etc/systemd/system/home-assistant@homeassistant.service; enabled)
   Active: active (running) since Fri 2017-04-07 15:10:26 PDT; 12min ago
 Main PID: 22869 (hass)
   CGroup: /system.slice/system-home\x2dassistant.slice/home-assistant@homeassistant.service
           └─22869 /srv/homeassistant/bin/python3 /srv/homeassistant/bin/hass -c /home/homeassistant/.homeassistant

```
Is there something else fundamentally wrong?
Downgrading to 0.2.3 fixes everything again :-o

**Comment by mweinelt** [comment]
Try `sudo journalctl -u home-assistant@homeassistant`

**Comment by rytilahti** [comment]
Looks like your home directory for homeassistant is /home/homeassistant/.homeassistant/ so you should find the log file in /home/homeassistant/.homeassistant/home-assistant.log

**Comment by chairstacker** [comment]
Thanks rytilahti - this is what I can find in the logfile related to tplink and pyHS100:

```
(homeassistant) homeassistant@GerstMeyersPi4:~/.homeassistant$ grep "tplink" home-assistant.log
17-04-07 15:59:56 INFO (MainThread) [homeassistant.loader] Loaded switch.tplink from homeassistant.components.switch.tplink
17-04-07 15:59:57 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tplink
17-04-07 15:59:57 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform tplink
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/switch/tplink.py", line 36, in setup_platform
17-04-07 15:59:57 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tplink
17-04-07 15:59:57 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform tplink
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/switch/tplink.py", line 36, in setup_platform
17-04-07 15:59:57 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tplink
17-04-07 15:59:57 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform tplink
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/switch/tplink.py", line 36, in setup_platform

(homeassistant) homeassistant@GerstMeyersPi4:~/.homeassistant$ grep "pyHS100" home-assistant.log
    from pyHS100 import SmartPlug
  File "/home/homeassistant/.homeassistant/deps/pyHS100/__init__.py", line 4, in <module>
    from pyHS100.pyHS100 import SmartBulb, SmartPlug, TPLinkSmartHomeProtocol, SmartPlugException
  File "/home/homeassistant/.homeassistant/deps/pyHS100/pyHS100.py", line 20, in <module>
    from pyHS100 import SmartPlug
  File "/home/homeassistant/.homeassistant/deps/pyHS100/__init__.py", line 4, in <module>
    from pyHS100.pyHS100 import SmartBulb, SmartPlug, TPLinkSmartHomeProtocol, SmartPlugException
  File "/home/homeassistant/.homeassistant/deps/pyHS100/pyHS100.py", line 20, in <module>
    from pyHS100 import SmartPlug
  File "/home/homeassistant/.homeassistant/deps/pyHS100/__init__.py", line 4, in <module>
    from pyHS100.pyHS100 import SmartBulb, SmartPlug, TPLinkSmartHomeProtocol, SmartPlugException
  File "/home/homeassistant/.homeassistant/deps/pyHS100/pyHS100.py", line 20, in <module>
```

**Comment by rytilahti** [comment]
Please look into the files or grep with -A accompanied with enough lines to get the real error messages. Those are just saying that it fails in import but nothing more. The best way to do is to just open the log file with an editor and check the whole error backtrace.

**Comment by chairstacker** [comment]
Is this better?

```
17-04-07 16:30:35 INFO (MainThread) [homeassistant.components.switch] Setting up switch.tplink
17-04-07 16:30:35 INFO (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=config>
17-04-07 16:30:35 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=camera.outdoorcam, old_state=None, new_state=<state camera.outdoorcam=idle; friendly_name=OutdoorCam, entity_picture=/api/camera_proxy/camera.outdoorcam?token=da8cae8f62bd20d5c122bea4d1f463f40704a176cbfa4ccb7d9313f8f062246a, access_token=da8cae8f62bd20d5c122bea4d1f463f40704a176cbfa4ccb7d9313f8f062246a @ 2017-04-07T16:30:35.587022-07:00>>
17-04-07 16:30:35 INFO (MainThread) [homeassistant.setup] Setting up frontend
17-04-07 16:30:35 INFO (MainThread) [homeassistant.core] Bus:Handling <Event component_loaded[L]: component=camera>
17-04-07 16:30:35 ERROR (MainThread) [homeassistant.components.switch] Error while setting up platform tplink
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/helpers/entity_component.py", line 153, in _async_setup_platform
    entity_platform.schedule_add_entities, discovery_info
  File "/usr/lib/python3.4/asyncio/futures.py", line 388, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 286, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/switch/tplink.py", line 36, in setup_platform
    from pyHS100 import SmartPlug
  File "/home/homeassistant/.homeassistant/deps/pyHS100/__init__.py", line 4, in <module>
    from pyHS100.pyHS100 import SmartBulb, SmartPlug, TPLinkSmartHomeProtocol, SmartPlugException
  File "/home/homeassistant/.homeassistant/deps/pyHS100/pyHS100.py", line 20, in <module>
    from future.utils import raise_from
ImportError: No module named 'future'

```

**Comment by rytilahti** [comment]
I have created a pull request to fix this, currently you can just run "pip install future" to make it work again. Thanks for your report and please let us know if it helps!

**Comment by chairstacker** [comment]
This did the trick, thanks for your help and your patience - highly appreciated!

I'm back where I was before upgrading to 0.2.4.1, i.e. my TPLink switches are showing up, but my TPLink light bulbs are not :-S

**Comment by rytilahti** [comment]
You mean in the homeassistant or in pyhs100 utility? The bulbs are not currently supported by homeassistant, see the discussion in https://community.home-assistant.io/t/tp-link-bulbs-lb100-lb110-and-lb120/9213/20 .

For pyhs100 util could you please check if they are detected correctly? https://github.com/GadgetReactor/pyHS100#discovering-devices

**Comment by chairstacker** [comment]
If you look further down in that thread it seems like some folks seem to have made the lightbulbs work.

Happy to check if the bulbs are detected correctly, but - you know by now I'm a noob ;-) - I would need some more details on how to do this.

**Comment by rytilahti** [comment]
Yes, it'll be still some effort to get a proper homeassistant support for those bulbs, but in the meantime you can click on the second link I gave to see if your bulbs are now detected properly with the backend library ;-) If they are detected and the switch works, then you'll just have to wait until someone finishes the homeassistant support and this task can be closed.

**Comment by chairstacker** [comment]
I had another issue that I had 'fixed' incorrectly, but now I am able to see the lightbulbs in HASS and switch them on.
There is an issue still with switching them off but I will try to solve this somewhere else.

Thank you again for your patience and your explanations!

**Comment by rytilahti** [comment]
This has been fixed already, so closing. Just for the reference for bulb support in homeassistant here's the thread: https://community.home-assistant.io/t/tp-link-bulbs-lb100-lb110-and-lb120/9213/33 .
