### ISSUE TITLE
Change to description

### ISSUE THREAD

**Issue by kdschlosser** [GadgetReactor/pyHS100#62]
The description currently states that this is only for switches which at this point i think that it controls all devices. but also in the README.md is states there are no bulb specific commands. 

I know this would be hard to consider but instead of pyHS100 for the name something like pyTPLink or pyTPLinkAPI may be more suitable. 

just a suggestion. because this has grown beyond controlling just the switches.

**Comment by kirichkov** [comment]
Yeah, we've already discussed changing the name. https://github.com/GadgetReactor/pyHS100/issues/40#issuecomment-287198977

The main reason why switches and bulbs are not listed in the readme is we don't have enough direct feedback about those and none of us has anything else but power plugs.

**Comment by kdschlosser** [comment]
Ok cool. Didn't know the name was already discussed. I am working through the bulb changes. Now. And there are a couple of them so far. I will open another issue to discuss these
