### ISSUE TITLE
LB100 changes in API

### ISSUE THREAD

**Issue by kdschlosser** [GadgetReactor/pyHS100#63]
Ok so this is what I have thus far. 

mic_mac instead of mac
fwId is not supported
time get_time not supported
time get_timezone not supported

I will update this if I find anything else not working. I have a couple of people using the GUI and Event front end I made up for this. So getting real-world information on what works and what doesn't should help. Ideally we will need to go down the line of all of the various model numbers. I am not sure which models are available in the US I am going to have a look see. They aren't very expensive so if they are all available I will go ahead and purchase them. I can provide the following if it will help. VPN access via a dedicated router. and / VM's with almost any OS of your choosing. If the OS supports device redirection then you can use that as well. You would have to let me know how many cores and how much ram you would want for the VM. And I also have a Macintosh I can dust off and get some form of a remote desktop running on it. Let me know if this will help.

**Comment by rytilahti** [comment]
These changes have been afaik already incorporated, so closing this.
