### ISSUE TITLE
discovery includes MAC information

### ISSUE THREAD

**Issue by geneliu** [GadgetReactor/pyHS100#64]
Wonder if we can enhance the discovery function to include MAC of the node?

**Comment by geneliu** [comment]
This is very useful when the smart plug is in DHCP environment only.

**Comment by rytilahti** [comment]
In what format you would like to have it? The sys_info returned by the discovery already contains the mac, but the one from the wire (which is what you probably want?) is not exposed.

**Comment by kdschlosser** [comment]
I have a nice little code piece that can obtain a devices true mac based on IP and without using subprocess to run ping and capture the output either :) funny thing is I just keyed it up about a week ago to send a WOL packet based on IP alone. So this can be done if it is something that the maintainers feel should be added or not. Or if it should be something the user should do themselves. But if you want the code for it drop a line. It's actually very small maybe 8 - 10 lines of code.

**Comment by geneliu** [comment]
Thank you @rytilahti for your quick response! I found that both CLI and the static method of 'discover' have the mac data there already. The json format is pretty good. I think no code change/enhancement needed.

**Comment by geneliu** [comment]
@kdschlosser 
If you can post your code snippets somewhere or here that would be helpful.
Thanks,
Gene

**Comment by kdschlosser** [comment]
here is the code for getting the mac address, it's a little longer then 10 lines but it is still very small

usage: print get_mac_address('192.168.1.1')

    import struct
    import ctypes


    def get_mac_address(ip_address):
        arp = ctypes.windll.Iphlpapi.SendARP
        addr = ctypes.windll.wsock32.inet_addr(ip_address)

        hw_address = ctypes.c_buffer(6)
        add_long = ctypes.c_ulong(ctypes.sizeof(hw_address))

        arp(addr, 0, ctypes.byref(hw_address), ctypes.byref(add_long))

        res = []

        for val in struct.unpack('BBBBBB', hw_address):
            if val > 15:
                replace_str = '0x'
            else:
                replace_str = 'x'

            res.append(hex(val).replace(replace_str, '').upper())

        return ':'.join(res)

**Comment by rytilahti** [comment]
Closing this as MAC is available in the payload.
