### ISSUE TITLE
Getting python errors?

### ISSUE THREAD

**Issue by Flizzzard** [GadgetReactor/pyHS100#68]
Hi guys, not sure if this is down to my inexperience or whatever but I've had a previous library of pyHS100 working fine, and decided to download a zip of a more recent version today. 

I've effectively replaced the psHS100 folder, but in my code I now get an error originating from psHS100.py

```
File "pyHS100.py", line 65
    raise SmartDeviceException('Communication error') from ex
                                                         ^
SyntaxError: invalid syntax
```

Any ideas? I've reverted back to the previous library I was using assuming there are syntax errors in the current version of the library...

**Comment by kirichkov** [comment]
What python version are you using?

Can you run `python --version` and paste the result.

**Comment by Flizzzard** [comment]
It's version 2.7.9 I believe. Is that compatible with the current release? I will double check later, but I've just checked the version on a machine that I think on an identical release and it's 2.7.9...

Thanks,
________________________________

**Comment by rytilahti** [comment]
Yes, the currently (unreleased) versions do not support python 2 anymore, and they also have SmartDeviceException instead of SmartPlugException like used to be, so if you are using the library directly you need to adapt that too.

**Comment by rytilahti** [comment]
Closing this as python2 is not anymore supported at this point.
