### ISSUE TITLE
home-assistant is still pulling down 0.2.0 instead of new 0.2.1

### ISSUE THREAD

**Issue by smaggard** [GadgetReactor/pyHS100#7]
Can you please submit the code to home-assistant to use the new version supporting more models?

**Comment by GadgetReactor** [comment]
ok. someone raised a PR previously for this so was waiting to see if that
cleared. let me check and i will raise a new PR if required

**Comment by rytilahti** [comment]
Any news on this?

**Comment by GadgetReactor** [comment]
It's been updated - https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/switch/tplink.py 

The new version should be pulled when HA is updated.

**Comment by GadgetReactor** [comment]
Sorry, I checked and it was pulling the wrong version still. the pull request has been approved for HA-dev. Please wait for the next version thank you!
