### ISSUE TITLE
Discover devices in the network

### ISSUE THREAD

**Issue by Vikum94** [GadgetReactor/pyHS100#79]
I recently wrote a script to find devices and then use the library to control a WiFi plug. I think it would be easy if the library can include a device search in the network, so that users can find the device IP addresses.

**Comment by kirichkov** [comment]
This got merged 2 days ago in https://github.com/GadgetReactor/pyHS100/pull/71

**Comment by Vikum94** [comment]
I think it is better if it is mentioned in the README. How to use it. Thank you.

**Comment by rytilahti** [comment]
Created #80. That code from #71 is still unreleased but it was already possible beforehand to discover the devices as shown in README.md: https://github.com/GadgetReactor/pyHS100#discovering-devices . The new functionality will make it more elegant and easy-to-use for 3rd party libraries and command-line users.

**Comment by rytilahti** [comment]
https://github.com/GadgetReactor/pyHS100/pull/88/commits/004f43f05738d6ac73cf8b82ff8241616afcc8f9 fixes this I hope.

**Comment by rytilahti** [comment]
Please check out the updated README: https://github.com/GadgetReactor/pyHS100#discovering-devices-1 . If there are some parts which are unclear, feedback & pull requests are very welcome.
