### ISSUE TITLE
brightness is 100% when dark bulb set to on in scene

### ISSUE THREAD

**Issue by githubbuh** [GadgetReactor/pyHS100#83]
Here is the use case.

turn the bulb off, maybe like this:
scene:
  - name: livingroom dark
     entities:
         light.lb1201
           state: off

then, turn the bulb on, maybe like this:
  - name: livingroom motion
     entities: 
         light.lb1201
         state: on
         brightness: 5

notice that the light turns on, but brightness is full
then call the livingroom.motion scene again without turning off the light
notice that the light is now at brightness: 5

the behavior suggests that turning on a bulb that is in a state of 'off' does not consider the requested brightness setting.

however, here is another possible cause.  after doing some testing this morning, i think the power state of the LB120 at turn on is influenced by how the bulb has been configured in KASA.  For instance, i had one bulb that was configured to turn on based upon last power setting and another that was configured to turn own based upon a preset.  this is still very much a hunch and i would suggest that it deserves further investigation.  the two bulbs behave differently when turned on from scenes that have brightness settings.  the bulb set to open using preset always came on bright.  after i changed it to come on from last power setting, that it what is does now when i turn it on from hass scenes.  it will always turn on using the brightness from the last scene in which the bulb was on.

homeassistant version 0.51.2
ubuntu 16.x
LB120 bulbs

happy to provide log content.  just not sure how to get what you would find useful
hope this helps

**Comment by rytilahti** [comment]
How does the communication look like? Is it working fine with the command line utility? In the code the library handles setting those separately depending on the state of the bulb, so it could be possible that this is an issue with homeassistant instead of this library.

P.S. Could you please provide `pyhs100 sysinfo` (after masking the IDs if you want so), it's the only bulb we are missing an entry in https://github.com/GadgetReactor/pyHS100/blob/master/pyHS100/tests/fakes.py

**Comment by githubbuh** [comment]
Here is the sysinfo for one of my LB120 blubs.

[pyhs100sysinfo.txt](https://github.com/GadgetReactor/pyHS100/files/1247865/pyhs100sysinfo.txt)

**Comment by githubbuh** [comment]
I removed my LB120 from Kasa, added is back to provision network access, and made no configuration changes to the bulb in Kasa.

Using hass, i activated a scene that turned the bulb on and checked with the command line to see that brightness was 1.  I then activated a scene that turned the bulb off.  Using the command line, i verified that brightness  was 1.  I then activated a scene that set the brightness to 39 and verified that with the command line.  I activated a scene to turn off the light.  I then activated the first scene, which should have set brightness to 1.  But, the command line confirmed that brightness was 39.

This pretty much confirms that when the light is turned on, the brightness defaults to what the light has stored as its last setting.  The brightness provided in the scene has no influence.

hope this helps.

**Comment by gollo** [comment]
I'm pretty sure this bug was addressed in this PR [8780](https://github.com/home-assistant/home-assistant/pull/8780), which has been merged but not in time for 0.51.2. In this PR, the bulb is activated and then brightness modified when turned on, previously the brightness was modified then the bulb turned on, and that doesn't work.  You could take [this](https://raw.githubusercontent.com/home-assistant/home-assistant/dev/homeassistant/components/light/tplink.py) version to test with if you like or wait for the next release.

**Comment by githubbuh** [comment]
Totally makes sense.  I will give the new version a try this evening.On Aug 24, 2017, at 12:56 AM, Sean Gollschewsky <notifications@github.com> wrote:I'm pretty sure this bug was addressed in this PR 8780, which has been merged but not in time for 0.51.2. In this PR, the bulb is activated and then brightness modified when turned on, previously the brightness was modified then the bulb turned on, and that doesn't work.  You could take this version to test with if you like or wait for the next release.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/GadgetReactor/pyHS100","title":"GadgetReactor/pyHS100","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/GadgetReactor/pyHS100" class="">https://github.com/GadgetReactor/pyHS100</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gollo in #83: I'm pretty sure this bug was addressed in this PR [8780](<a href="https://github.com/home-assistant/home-assistant/pull/8780" class="">https://github.com/home-assistant/home-assistant/pull/8780</a>), which has been merged but not in time for 0.51.2. In this PR, the bulb is activated and then brightness modified when turned on, previously the brightness was modified then the bulb turned on, and that doesn't work.  You could take [this](<a href="https://raw.githubusercontent.com/home-assistant/home-assistant/dev/homeassistant/components/light/tplink.py" class="">https://raw.githubusercontent.com/home-assistant/home-assistant/dev/homeassistant/components/light/tplink.py</a>) version to test with if you like or wait for the next release."}],"action":{"name":"View Issue","url":"<a href="https://github.com/GadgetReactor/pyHS100/issues/83#issuecomment-324562183" class="">https://github.com/GadgetReactor/pyHS100/issues/83#issuecomment-324562183</a>"}}}

**Comment by rytilahti** [comment]
If the linked PR fixes this issue, then there is still a problem with pyhs100's bulb support though. I think it should be possible to change the settings when the bulb is off, but unfortunately testing such is hard without having a bulb. If the fix on that PR works for you, that's good! Thanks for the sysinfo output, I'll add it to our test-suite.

**Comment by gollo** [comment]
I agree it would be nice to do that, but not sure how.  The current way
it's manipulated results in this for LB110

*20:05 $ pyhs100 --bulb --ip 192.168.0.112*
== Downstairs - LB110(EU) ==
OFF
IP address: 192.168.0.112
Brightness: 50
Is dimmable: True
== Generic information ==
Time:         None
Hardware:     1.0
Software:     1.5.5 Build 170623 Rel.090105
MAC (rssi):   50C7BF7BE306 (-64)
WARNING:pyHS100.smartdevice:Unsupported device location.
Location:     {'latitude': None, 'longitude': None}
== Emeter ==
Current state: {'power_mw': 0}

*20:16 $ python3.6 test_lb110.py *
Initial State: OFF
Initial Brightness: 50
Set brightness to 23 with bulb off
Brightness now 50
Turn on
State: ON
Brightness: 50
Set brightness to 23 with bulb on
Brightness now 23
Turn off
State: OFF
Brightness: 23

(Code attached, running on master)

So it doesn't change when off. There may be another way but I haven't come
across it.
