### ISSUE TITLE
Cant run tox. error.

### ISSUE THREAD

**Issue by saket404** [GadgetReactor/pyHS100#84]
![capture](https://user-images.githubusercontent.com/26710708/29707352-2cfcb89c-89af-11e7-8c31-4593f6fd7afd.PNG)

We run on windows.

**Comment by rytilahti** [comment]
Looks like the tests were run fine, however, coveralls works only when run with Travis and python3.4 and python3.5 when those are installed. Do you see some other errors why py36 fails?
