### ISSUE TITLE
Discover mode not available/documented in library mode

### ISSUE THREAD

**Issue by mikaelholber** [GadgetReactor/pyHS100#86]
I cannot find any references or managed to use the discover mode when using pyHS100 as library in python 2.7.9.

I can import SmartPlug and SmartBulb but not Discover-classes. If possible, please provide an example in the read me. Looking for how to extract the IP-address and device names from all devices on the network to use directly in my python scripts.

Thank you!
Mikael

**Comment by gollo** [comment]
This depends on the version of pyHS100 you are using. If 0.2.4.2, you are limited to
```
TPLinkSmartHomeProtocol.discover(timeout=5)
```
which will return you a list of devices by ip and their sysinfo, which you can query for name, eg
```
from pyHS100 import TPLinkSmartHomeProtocol, SmartBulb, SmartPlug
devices = TPLinkSmartHomeProtocol.discover(2)
for dev in devices:
    print(dev['ip'])
    print(dev['sys_info']['system']['get_sysinfo']['alias'])
```
If you just want IP/name.
If you then want to create SmartBulb and SmartPlug objects you have to determine the type yourself from the sysinfo (look for mic_type=IOT.SMARTBULB or type=IOT.SMARTPLUGSWITCH respectively) then you can create the objects as usual
```
bulb = SmartBulb(dev['ip'])
```
etc.
The upcoming 0.3 release has a standalone Discover class which will return the object instances of the appropriate class directly, but unfortunately for your use case drops python2 support (see [here](https://github.com/GadgetReactor/pyHS100/issues/80).

**Comment by mikaelholber** [comment]
Thank you for your swift reply. I will try this in the next time when I have some time.

**Comment by mikaelholber** [comment]
So I tried both with the cli and python class. However, my machine has several interfaces and I guess this confuses it. Not even with 100s of discovery time it finds my device. Maybe it would be possible to specify device or subnet in the future? Thank you for your support!

**Comment by gollo** [comment]
Which device are you using? Are you saying the device is on a different subnet? If so, the discovery is unlikely to work, it uses a broadcast to find the devices. The only way is to know the IP (you can probably find in your router DHCP client list, or from the KASA app). Once you have that, you can, on command line

```
$ pyhs100  --IP xxx.xxx.xxx.xxx <cmd>
```
or
```
export PYHS100_IP=xxx.xxx.xxx.xxx
pyhs100 .on
pyhs100.off
```
where commands are listed with pyhs100 --help
or as library
```
from pyHS100 import SmartPlug
plug = SmartPlug("xxx.xxx.xxx.xxx")
print(plug.alias)
plug.state("ON")
print(plug.state)
plug.state("OFF")
```
See the pyHS100.py code for available methods.
