### ISSUE TITLE
Error importing to Python on Raspberry Pi

### ISSUE THREAD

**Issue by jwtaylor310** [GadgetReactor/pyHS100#87]
I am trying to implement pyHS100 on a Raspberry Pi 3.  Python throws an "invalid syntax" error at the line "from phHS100 import SmartPlug:: 

**Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from pyHS100 import SmartPlug
  File "/home/pi/Programs/test/pyHS100/pyHS100/__init__.py", line 16, in <module>
    from .smartdevice import SmartDevice
  File "/home/pi/Programs/test/pyHS100/pyHS100/smartdevice.py", line 65
    raise SmartDeviceException('Communication error') from ex
                                                                                        ^
SyntaxError: invalid syntax

Any help with this will be MOST appreciated!  

Thank you!

**Comment by jeffsf** [comment]
Which version of Python 3 are you running?

**Comment by rytilahti** [comment]
AFAIK `raise X from` is supported from 3.0 onwards, so sounds like you are running it through python2 interpreter. Could you verify that you are using python3?

**Comment by jwtaylor310** [comment]
I am embarrassed to report that I was testing with command "python" instead of "python3".  That means I was doing the test with version 2.7.9.  Now with "python3" the version reports as 3.4.2 and with that change pyHS100 works beautifully.  Thanks to jeffsf and rytilahti for getting me on the right track and to all who have done the work to make this program available!

**Comment by jwtaylor310** [comment]
Hello;

 

You are exactly right.  I found that I had to start the program with the command “python3” instead of just “python” and when I do that everything works without error.

 

Thank you for your help – it is most appreciated!

 

--John

**Comment by jwtaylor310** [comment]
Hello;

 

I was starting the program with the command “python” which I now realize starts version 27.9.  I found that by using the command “python3” I get version 3.4.2 and pyHS100  works without error.

 

That is on my Raspberry which is what I want to use for a dedicated automation controller.  I have now also install python 3.5.3 on a Windows 10 PC and the programs work in that environment too.

 

Thank you for your help – it is most appreciated!

 

--John
