### ISSUE TITLE
types.py clashes with Python standard lib 'types'

### ISSUE THREAD

**Issue by Snipsi** [GadgetReactor/pyHS100#94]
Please consider renaming the types.py to device_types.py or similar, as it causes an import error in the click package when running cli.py:

       ImportError: cannot import name 'MappingProxyType'

Reason: Python searches for 'MappingProxyType' in types.py instead of the Python standard library 'types'.

**Comment by rytilahti** [comment]
The `cli.py` should not be run as it is but through its installed `pyhs100` file. However, I think the concern is fair enough, and considering the fact that only the exception class is used from the file, I'd propose just moving the exception to `SmartDevice` and getting rid of the whole file.
