### ISSUE TITLE
Increase the test coverage

### ISSUE THREAD

**Issue by rytilahti** [GadgetReactor/pyHS100#97]
Increasing the test coverage would be a nice set of tasks for Hacktoberfest if someone wants to pursue that. See https://coveralls.io/github/GadgetReactor/pyHS100?branch=master for possible places for improvement.

**Comment by peterjgrainger** [comment]
Looks like cli.py is at 0%, I'll have a go at that one if you want.  I'll let you know any progress tomorrow :)

**Comment by rytilahti** [comment]
@TheSmokingGnu I'm not sure if it is worth to test the client itself, the library parts are much more important (and probably easier to test?) in my opinion :-) However, if you like to add tests for the cli, that would also be appreciated!

**Comment by peterjgrainger** [comment]
Hrmmm...  Maybe I'll start with smartbulb.py first and then give the cli a go.

**Comment by rytilahti** [comment]
I stumbled upon this http://click.pocoo.org/5/testing/ so maybe testing the cli is not so cumbersome as I thought it would be.

**Comment by peterjgrainger** [comment]
Thanks.  I'm going through the bulb test, pretty straight forward.  I'll
put in a or for that first :)

**Comment by rytilahti** [comment]
This is too generic and the coverage got already better with the referenced PR, so I'm closing this.
